# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Xilinx/Projects/Electronic Monitoring Unit/EMU/EMU.srcs/sources_1/bd/EMU_design/ip/EMU_design_microblaze_0_0/EMU_design_microblaze_0_0.xci
# IP: The module: 'EMU_design_microblaze_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx/Projects/Electronic Monitoring Unit/EMU/EMU.gen/sources_1/bd/EMU_design/ip/EMU_design_microblaze_0_0/EMU_design_microblaze_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'EMU_design_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Xilinx/Projects/Electronic Monitoring Unit/EMU/EMU.gen/sources_1/bd/EMU_design/ip/EMU_design_microblaze_0_0/EMU_design_microblaze_0_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'EMU_design_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Xilinx/Projects/Electronic Monitoring Unit/EMU/EMU.gen/sources_1/bd/EMU_design/ip/EMU_design_microblaze_0_0/EMU_design_microblaze_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'EMU_design_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/Xilinx/Projects/Electronic Monitoring Unit/EMU/EMU.srcs/sources_1/bd/EMU_design/ip/EMU_design_microblaze_0_0/EMU_design_microblaze_0_0.xci
# IP: The module: 'EMU_design_microblaze_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx/Projects/Electronic Monitoring Unit/EMU/EMU.gen/sources_1/bd/EMU_design/ip/EMU_design_microblaze_0_0/EMU_design_microblaze_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'EMU_design_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Xilinx/Projects/Electronic Monitoring Unit/EMU/EMU.gen/sources_1/bd/EMU_design/ip/EMU_design_microblaze_0_0/EMU_design_microblaze_0_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'EMU_design_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Xilinx/Projects/Electronic Monitoring Unit/EMU/EMU.gen/sources_1/bd/EMU_design/ip/EMU_design_microblaze_0_0/EMU_design_microblaze_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'EMU_design_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
