# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Xilinx/Projects/ElectronicMonitoringUnit/EMU/EMU.srcs/sources_1/bd/EMU_design/ip/EMU_design_lmb_bram_0/EMU_design_lmb_bram_0.xci
# IP: The module: 'EMU_design_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx/Projects/ElectronicMonitoringUnit/EMU/EMU.gen/sources_1/bd/EMU_design/ip/EMU_design_lmb_bram_0/EMU_design_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'EMU_design_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/Xilinx/Projects/ElectronicMonitoringUnit/EMU/EMU.srcs/sources_1/bd/EMU_design/ip/EMU_design_lmb_bram_0/EMU_design_lmb_bram_0.xci
# IP: The module: 'EMU_design_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx/Projects/ElectronicMonitoringUnit/EMU/EMU.gen/sources_1/bd/EMU_design/ip/EMU_design_lmb_bram_0/EMU_design_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'EMU_design_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
